### ISSUE TITLE
Access to special pages fails

### ISSUE THREAD

**Issue by jueadams** [ekristen/wikidocs#3]
Dear Erik,

many thanks for your project WikiDocs. It looks brilliant, but I ran in some pitfalls. First, no special pages are accessible. Maybe a rewrite rule is missing/not correct?

## 1. Access to special pages (e.g /Special:UserLogin) fails

Accessing the special page UserLogin failed using the Log in button. The resulting uri is:

  http://docs.test/User:Lxadm

If the uri is given that way:

  http://docs.test/index.php?title=Special:UserLogin

the page can be opened and a login is possible.

Any help is very welcome. 

Thanks a lot,
Juergen

From error.log (rewrite logs)
====================

// http://docs.test/User:Lxadm
//
[Tue Dec 17 18:21:46.963573 2013] [ssl:warn] [pid 5948:tid 364] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Tue Dec 17 18:21:47.013573 2013] [mpm_winnt:notice] [pid 5948:tid 364] AH00455: Apache/2.4.7 (Win32) OpenSSL/0.9.8y PHP/5.4.22 configured -- resuming normal operations
[Tue Dec 17 18:21:47.013573 2013] [mpm_winnt:notice] [pid 5948:tid 364] AH00456: Apache Lounge VC10 Server built: Nov 26 2013 16:07:35
[Tue Dec 17 18:21:47.013573 2013] [core:notice] [pid 5948:tid 364] AH00094: Command line: 'C:\\multiplatform\\xammp\\apache\\bin\\httpd.exe -d C:/MultiPlatform/XAMMP/apache'
[Tue Dec 17 18:21:47.013573 2013] [mpm_winnt:notice] [pid 5948:tid 364] AH00418: Parent: Created child process 3512
[Tue Dec 17 18:21:48.143574 2013] [ssl:warn] [pid 3512:tid 256] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Tue Dec 17 18:21:48.203574 2013] [mpm_winnt:notice] [pid 3512:tid 256] AH00354: Child: Starting 150 worker threads.
[Tue Dec 17 18:21:50.953578 2013] [rewrite:trace2] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64533] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d686a8/initial] init rewrite engine with requested uri /Special:UserLogin, referer: http://docs.test/Documentation
[Tue Dec 17 18:21:50.953578 2013] [rewrite:trace1] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64533] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d686a8/initial] pass through /Special:UserLogin, referer: http://docs.test/Documentation
[Tue Dec 17 18:21:50.953578 2013] [core:error] [pid 3512:tid 1708] (20024)The given path is misformatted or contained invalid characters: [client 192.168.13.100:64533] AH00127: Cannot map GET /Special:UserLogin HTTP/1.1 to file, referer: http://docs.test/Documentation
[Tue Dec 17 18:21:50.953578 2013] [rewrite:trace2] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64533] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d69988/initial/redir#1] init rewrite engine with requested uri /error/HTTP_FORBIDDEN.html.var, referer: http://docs.test/Documentation
[Tue Dec 17 18:21:50.953578 2013] [rewrite:trace1] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64533] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d69988/initial/redir#1] pass through /error/HTTP_FORBIDDEN.html.var, referer: http://docs.test/Documentation
[Tue Dec 17 18:21:50.953578 2013] [authz_core:error] [pid 3512:tid 1708] [client 192.168.13.100:64533] AH01630: client denied by server configuration: C:/xampp, referer: http://docs.test/Documentation

// http://docs.test/index.php?title=Special:UserLogin
//
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace2] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] init rewrite engine with requested uri /index.php, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace1] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] pass through /index.php, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/docs.js -> extensions/PonyDocs/js/docs.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] applying pattern '^Documentation/$' to uri 'extensions/PonyDocs/js/docs.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/docs.js -> extensions/PonyDocs/js/docs.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] applying pattern '^Documentation:(.*):(.*):(.*):(.*):(.*)' to uri 'extensions/PonyDocs/js/docs.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/docs.js -> extensions/PonyDocs/js/docs.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] applying pattern '^$' to uri 'extensions/PonyDocs/js/docs.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/docs.js -> extensions/PonyDocs/js/docs.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] applying pattern '^Main_Page$' to uri 'extensions/PonyDocs/js/docs.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/docs.js -> extensions/PonyDocs/js/docs.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] applying pattern '^' to uri 'extensions/PonyDocs/js/docs.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace1] [pid 3512:tid 1692] mod_rewrite.c(468): [client 192.168.13.100:64549] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#85800f8/initial] [perdir E:/www/docs/] pass through E:/www/docs/extensions/PonyDocs/js/docs.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/jquery.json-2.2.min.js -> extensions/PonyDocs/js/jquery.json-2.2.min.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace1] [pid 3512:tid 1684] mod_rewrite.c(468): [client 192.168.13.100:64550] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#858a120/initial] [perdir E:/www/docs/] pass through E:/www/docs/extensions/PonyDocs/js/jquery.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/index.php -> index.php, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] applying pattern '^Documentation/$' to uri 'index.php', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/index.php -> index.php, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] applying pattern '^Documentation:(.*):(.*):(.*):(.*):(.*)' to uri 'index.php', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/index.php -> index.php, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] applying pattern '^$' to uri 'index.php', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/index.php -> index.php, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] applying pattern '^Main_Page$' to uri 'index.php', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/index.php -> index.php, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] applying pattern '^' to uri 'index.php', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace1] [pid 3512:tid 1708] mod_rewrite.c(468): [client 192.168.13.100:64541] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d746d8/initial] [perdir E:/www/docs/] pass through E:/www/docs/index.php, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] applying pattern '^Documentation/$' to uri 'extensions/PonyDocs/js/jquery.json-2.2.min.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/jquery.json-2.2.min.js -> extensions/PonyDocs/js/jquery.json-2.2.min.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] applying pattern '^Documentation:(.*):(.*):(.*):(.*):(.*)' to uri 'extensions/PonyDocs/js/jquery.json-2.2.min.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/jquery.json-2.2.min.js -> extensions/PonyDocs/js/jquery.json-2.2.min.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] applying pattern '^$' to uri 'extensions/PonyDocs/js/jquery.json-2.2.min.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/jquery.json-2.2.min.js -> extensions/PonyDocs/js/jquery.json-2.2.min.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] applying pattern '^Main_Page$' to uri 'extensions/PonyDocs/js/jquery.json-2.2.min.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] strip per-dir prefix: E:/www/docs/extensions/PonyDocs/js/jquery.json-2.2.min.js -> extensions/PonyDocs/js/jquery.json-2.2.min.js, referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace3] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] applying pattern '^' to uri 'extensions/PonyDocs/js/jquery.json-2.2.min.js', referer: http://docs.test/index.php?title=Special:UserLogin
[Tue Dec 17 18:24:14.163779 2013] [rewrite:trace1] [pid 3512:tid 1700] mod_rewrite.c(468): [client 192.168.13.100:64547] 192.168.13.100 - - [docs.test/sid#d4f6a8][rid#d6e6c0/initial] [perdir E:/www/docs/] pass through E:/www/docs/extensions/PonyDocs/js/jquery.json-2.2.min.js, referer: http://docs.test/index.php?title=Special:UserLogin

**Comment by ekristen** [comment]
Project is defunct, no issues will be addresses.

**Comment by JialuZhang** [comment]
@jueadams 

In your posted configuration,
```
RewriteEngine Off
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
