### ISSUE TITLE
.htaccess should be disabled for fresh install (setup)

### ISSUE THREAD

**Issue by jueadams** [ekristen/wikidocs#5]
Hi Erik,

I did a fresh installtion of the WikiDocs software on a Linux system but it fails because the productive .htaccess cause invalid rewriting for MediaWiki uri's for the setup. I simply renamed that file for installation and renamed it after set setup created a WikiDocs wiki.

Juergen

**Comment by ekristen** [comment]
Project is defunct, no issues will be addresses.
